### ISSUE TITLE
Doesn't work with Valkyrien Skies

### ISSUE THREAD

**Issue by allforone33** [Asek3/sodium-1.12#28]
### Bug Description

Doesn't work with Valkyrien Skies 1 (1.12).

### Reproduction Steps

Put Valkyrien Skies and Sodium in mod folder and launch the game. 

### Log File

[main/FATAL] [mixin]: Mixin apply for mod unknown-owner failed vintagium.mixins.json:features.world_ticking.MixinClientWorld from mod unknown-owner -> net.minecraft.client.multiplayer.WorldClient: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("NEW") on net/minecraft/client/multiplayer/WorldClient::redirectRandomTickRandom with priority 1000 cannot inject into net/minecraft/client/multiplayer/WorldClient::func_73029_E(III)V merged by org.valkyrienskies.mixin.client.multiplayer.MixinWorldClient with priority 1000 [PREINJECT Applicator Phase -> vintagium.mixins.json:features.world_ticking.MixinClientWorld from mod unknown-owner -> Prepare Injections ->  -> redirect$zlj000$redirectRandomTickRandom()Ljava/util/Random; -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("NEW") on net/minecraft/client/multiplayer/WorldClient::redirectRandomTickRandom with priority 1000 cannot inject into net/minecraft/client/multiplayer/WorldClient::func_73029_E(III)V merged by org.valkyrienskies.mixin.client.multiplayer.MixinWorldClient with priority 1000 [PREINJECT Applicator Phase -> vintagium.mixins.json:features.world_ticking.MixinClientWorld from mod unknown-owner -> Prepare Injections ->  -> redirect$zlj000$redirectRandomTickRandom()Ljava/util/Random; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[!mixinbooter-8.9.jar:?]
	at com.llamalad7.mixinextras.wrapper.InjectorWrapperImpl.prepare(InjectorWrapperImpl.java:51) ~[!mixinbooter-8.9.jar:?]
	at com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.prepare(WrapperInjectionInfo.java:57) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:377) [!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:240) [!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:208) [!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [!mixinbooter-8.9.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:957) [?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:902) [?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:885) [?:1.8.0_352]
	at net.minecraft.client.main.Main.main(SourceFile:38) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_352]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_352]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_352]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_352]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_352]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_352]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_352]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_352]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
 [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_352]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_352]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_352]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_352]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_352]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_352]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_352]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_352]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net.minecraft.client.multiplayer.WorldClient
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 14 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:957) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:902) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:885) ~[?:1.8.0_352]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:406) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:240) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:208) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[!mixinbooter-8.9.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:957) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:902) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:885) ~[?:1.8.0_352]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 14 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [vintagium.mixins.json:features.world_ticking.MixinClientWorld from mod unknown-owner] from phase [DEFAULT] in config [vintagium.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:655) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:605) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:393) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:240) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:208) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[!mixinbooter-8.9.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:957) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:902) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:885) ~[?:1.8.0_352]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("NEW") on net/minecraft/client/multiplayer/WorldClient::redirectRandomTickRandom with priority 1000 cannot inject into net/minecraft/client/multiplayer/WorldClient::func_73029_E(III)V merged by org.valkyrienskies.mixin.client.multiplayer.MixinWorldClient with priority 1000 [PREINJECT Applicator Phase -> vintagium.mixins.json:features.world_ticking.MixinClientWorld from mod unknown-owner -> Prepare Injections ->  -> redirect$zlj000$redirectRandomTickRandom()Ljava/util/Random; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[!mixinbooter-8.9.jar:?]
	at com.llamalad7.mixinextras.wrapper.InjectorWrapperImpl.prepare(InjectorWrapperImpl.java:51) ~[!mixinbooter-8.9.jar:?]
	at com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.prepare(WrapperInjectionInfo.java:57) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:377) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:240) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:208) ~[!mixinbooter-8.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[!mixinbooter-8.9.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:957) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:902) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:885) ~[?:1.8.0_352]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 14 more
[main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:246]: Failed to start Minecraft:
net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:101)
	at java.lang.System.exit(System.java:389)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exception in thread "main" net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:101)
	at java.lang.System.exit(System.java:389)
	at org.multimc.EntryPoint.main(EntryPoint.java:38)

**Comment by unilock** [comment]
This *particular* crash can be fixed by increasing the priority of Vintagium's [`MixinClientWorld`](https://github.com/Asek3/sodium-1.12/blob/29dc4a8d527c8a22dfca4c5ebce82303df2a0615/src/main/java/me/jellysquid/mods/sodium/mixin/features/world_ticking/MixinClientWorld.java) (i.e. to 1500), but given Valkyrien Skies requires rather large changes to Minecraft's rendering code, I wouldn't be surprised if another mixin (or several) fail to apply later.

Relevant VS mixin: https://github.com/ValkyrienSkies/Valkyrien-Skies/blob/2de196b93c5884990f1dbb8208c50d6586ee425e/src/main/java/org/valkyrienskies/mixin/client/multiplayer/MixinWorldClient.java

**Comment by Oregano1963** [comment]
How do I change the priority of MixinClientWorld?
